from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(634, 778)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.team1 = QtWidgets.QWidget(self.centralwidget)
        self.team1.setGeometry(QtCore.QRect(40, 10, 351, 651))
        self.team1.setObjectName("team1")
        self.player0FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player0FirstName.setGeometry(QtCore.QRect(40, 50, 101, 31))
        self.player0FirstName.setObjectName("player0FirstName")
        self.player1FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player1FirstName.setGeometry(QtCore.QRect(40, 80, 101, 31))
        self.player1FirstName.setObjectName("player1FirstName")
        self.player2FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player2FirstName.setGeometry(QtCore.QRect(40, 110, 101, 31))
        self.player2FirstName.setObjectName("player2FirstName")
        self.player3FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player3FirstName.setGeometry(QtCore.QRect(40, 140, 101, 31))
        self.player3FirstName.setObjectName("player3FirstName")
        self.player6FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player6FirstName.setGeometry(QtCore.QRect(40, 230, 101, 31))
        self.player6FirstName.setObjectName("player6FirstName")
        self.player5FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player5FirstName.setGeometry(QtCore.QRect(40, 200, 101, 31))
        self.player5FirstName.setObjectName("player5FirstName")
        self.player4FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player4FirstName.setGeometry(QtCore.QRect(40, 170, 101, 31))
        self.player4FirstName.setObjectName("player4FirstName")
        self.player7FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player7FirstName.setGeometry(QtCore.QRect(40, 260, 101, 31))
        self.player7FirstName.setObjectName("player7FirstName")
        self.player10FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player10FirstName.setGeometry(QtCore.QRect(40, 350, 101, 31))
        self.player10FirstName.setObjectName("player10FirstName")
        self.player9FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player9FirstName.setGeometry(QtCore.QRect(40, 320, 101, 31))
        self.player9FirstName.setObjectName("player9FirstName")
        self.player8FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player8FirstName.setGeometry(QtCore.QRect(40, 290, 101, 31))
        self.player8FirstName.setObjectName("player8FirstName")
        self.player11FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player11FirstName.setGeometry(QtCore.QRect(40, 380, 101, 31))
        self.player11FirstName.setObjectName("player11FirstName")
        self.player15FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player15FirstName.setGeometry(QtCore.QRect(40, 500, 101, 31))
        self.player15FirstName.setObjectName("player15FirstName")
        self.player12FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player12FirstName.setGeometry(QtCore.QRect(40, 410, 101, 31))
        self.player12FirstName.setObjectName("player12FirstName")
        self.player13FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player13FirstName.setGeometry(QtCore.QRect(40, 440, 101, 31))
        self.player13FirstName.setObjectName("player13FirstName")
        self.player14FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player14FirstName.setGeometry(QtCore.QRect(40, 470, 101, 31))
        self.player14FirstName.setObjectName("player14FirstName")
        self.player18FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player18FirstName.setGeometry(QtCore.QRect(40, 590, 101, 31))
        self.player18FirstName.setObjectName("player18FirstName")
        self.player17FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player17FirstName.setGeometry(QtCore.QRect(40, 560, 101, 31))
        self.player17FirstName.setObjectName("player17FirstName")
        self.player16FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player16FirstName.setGeometry(QtCore.QRect(40, 530, 101, 31))
        self.player16FirstName.setObjectName("player16FirstName")
        self.player19FirstName = QtWidgets.QPlainTextEdit(self.team1)
        self.player19FirstName.setGeometry(QtCore.QRect(40, 620, 101, 31))
        self.player19FirstName.setObjectName("player19FirstName")
        self.player6LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player6LastName.setGeometry(QtCore.QRect(150, 230, 101, 31))
        self.player6LastName.setObjectName("player6LastName")
        self.player9LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player9LastName.setGeometry(QtCore.QRect(150, 320, 101, 31))
        self.player9LastName.setObjectName("player9LastName")
        self.player1LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player1LastName.setGeometry(QtCore.QRect(150, 80, 101, 31))
        self.player1LastName.setObjectName("player1LastName")
        self.player12LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player12LastName.setGeometry(QtCore.QRect(150, 410, 101, 31))
        self.player12LastName.setObjectName("player12LastName")
        self.player2LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player2LastName.setGeometry(QtCore.QRect(150, 110, 101, 31))
        self.player2LastName.setObjectName("player2LastName")
        self.player4LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player4LastName.setGeometry(QtCore.QRect(150, 170, 101, 31))
        self.player4LastName.setObjectName("player4LastName")
        self.player14LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player14LastName.setGeometry(QtCore.QRect(150, 470, 101, 31))
        self.player14LastName.setObjectName("player14LastName")
        self.player18LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player18LastName.setGeometry(QtCore.QRect(150, 590, 101, 31))
        self.player18LastName.setObjectName("player18LastName")
        self.player13LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player13LastName.setGeometry(QtCore.QRect(150, 440, 101, 31))
        self.player13LastName.setObjectName("player13LastName")
        self.player0LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player0LastName.setGeometry(QtCore.QRect(150, 50, 101, 31))
        self.player0LastName.setObjectName("player0LastName")
        self.player15LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player15LastName.setGeometry(QtCore.QRect(150, 500, 101, 31))
        self.player15LastName.setObjectName("player15LastName")
        self.player5LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player5LastName.setGeometry(QtCore.QRect(150, 200, 101, 31))
        self.player5LastName.setObjectName("player5LastName")
        self.player8LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player8LastName.setGeometry(QtCore.QRect(150, 290, 101, 31))
        self.player8LastName.setObjectName("player8LastName")
        self.player11LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player11LastName.setGeometry(QtCore.QRect(150, 380, 101, 31))
        self.player11LastName.setObjectName("player11LastName")
        self.player10LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player10LastName.setGeometry(QtCore.QRect(150, 350, 101, 31))
        self.player10LastName.setObjectName("player10LastName")
        self.player17LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player17LastName.setGeometry(QtCore.QRect(150, 560, 101, 31))
        self.player17LastName.setObjectName("player17LastName")
        self.player3LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player3LastName.setGeometry(QtCore.QRect(150, 140, 101, 31))
        self.player3LastName.setObjectName("player3LastName")
        self.player19LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player19LastName.setGeometry(QtCore.QRect(150, 620, 101, 31))
        self.player19LastName.setObjectName("player19LastName")
        self.player16LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player16LastName.setGeometry(QtCore.QRect(150, 530, 101, 31))
        self.player16LastName.setObjectName("player16LastName")
        self.player7LastName = QtWidgets.QPlainTextEdit(self.team1)
        self.player7LastName.setGeometry(QtCore.QRect(150, 260, 101, 31))
        self.player7LastName.setObjectName("player7LastName")
        self.label = QtWidgets.QLabel(self.team1)
        self.label.setGeometry(QtCore.QRect(10, 110, 31, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.team1)
        self.label_2.setGeometry(QtCore.QRect(10, 260, 31, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.team1)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 31, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.team1)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 31, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.team1)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 31, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.team1)
        self.label_6.setGeometry(QtCore.QRect(10, 200, 31, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.team1)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 31, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.team1)
        self.label_8.setGeometry(QtCore.QRect(10, 320, 31, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.team1)
        self.label_9.setGeometry(QtCore.QRect(10, 380, 31, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.team1)
        self.label_10.setGeometry(QtCore.QRect(10, 410, 31, 31))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.team1)
        self.label_11.setGeometry(QtCore.QRect(10, 290, 31, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.team1)
        self.label_12.setGeometry(QtCore.QRect(10, 470, 31, 31))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.team1)
        self.label_13.setGeometry(QtCore.QRect(10, 350, 31, 31))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.team1)
        self.label_14.setGeometry(QtCore.QRect(10, 440, 31, 31))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.team1)
        self.label_15.setGeometry(QtCore.QRect(10, 530, 31, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.team1)
        self.label_16.setGeometry(QtCore.QRect(10, 590, 31, 31))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.team1)
        self.label_17.setGeometry(QtCore.QRect(10, 620, 31, 31))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.team1)
        self.label_18.setGeometry(QtCore.QRect(10, 500, 31, 31))
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.team1)
        self.label_20.setGeometry(QtCore.QRect(10, 560, 31, 31))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.team1)
        self.label_21.setGeometry(QtCore.QRect(10, 50, 31, 31))
        self.label_21.setObjectName("label_21")
        self.teamName = QtWidgets.QPlainTextEdit(self.team1)
        self.teamName.setGeometry(QtCore.QRect(90, 10, 104, 31))
        self.teamName.setObjectName("teamName")
        self.team2 = QtWidgets.QWidget(self.centralwidget)
        self.team2.setGeometry(QtCore.QRect(330, 10, 291, 651))
        self.team2.setObjectName("team2")
        self.player0FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player0FirstName_2.setGeometry(QtCore.QRect(40, 50, 101, 31))
        self.player0FirstName_2.setObjectName("player0FirstName_2")
        self.player1FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player1FirstName_2.setGeometry(QtCore.QRect(40, 80, 101, 31))
        self.player1FirstName_2.setObjectName("player1FirstName_2")
        self.player2FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player2FirstName_2.setGeometry(QtCore.QRect(40, 110, 101, 31))
        self.player2FirstName_2.setObjectName("player2FirstName_2")
        self.player3FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player3FirstName_2.setGeometry(QtCore.QRect(40, 140, 101, 31))
        self.player3FirstName_2.setObjectName("player3FirstName_2")
        self.player6FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player6FirstName_2.setGeometry(QtCore.QRect(40, 230, 101, 31))
        self.player6FirstName_2.setObjectName("player6FirstName_2")
        self.player5FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player5FirstName_2.setGeometry(QtCore.QRect(40, 200, 101, 31))
        self.player5FirstName_2.setObjectName("player5FirstName_2")
        self.player4FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player4FirstName_2.setGeometry(QtCore.QRect(40, 170, 101, 31))
        self.player4FirstName_2.setObjectName("player4FirstName_2")
        self.player7FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player7FirstName_2.setGeometry(QtCore.QRect(40, 260, 101, 31))
        self.player7FirstName_2.setObjectName("player7FirstName_2")
        self.player10FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player10FirstName_2.setGeometry(QtCore.QRect(40, 350, 101, 31))
        self.player10FirstName_2.setObjectName("player10FirstName_2")
        self.player9FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player9FirstName_2.setGeometry(QtCore.QRect(40, 320, 101, 31))
        self.player9FirstName_2.setObjectName("player9FirstName_2")
        self.player8FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player8FirstName_2.setGeometry(QtCore.QRect(40, 290, 101, 31))
        self.player8FirstName_2.setObjectName("player8FirstName_2")
        self.player11FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player11FirstName_2.setGeometry(QtCore.QRect(40, 380, 101, 31))
        self.player11FirstName_2.setObjectName("player11FirstName_2")
        self.player15FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player15FirstName_2.setGeometry(QtCore.QRect(40, 500, 101, 31))
        self.player15FirstName_2.setObjectName("player15FirstName_2")
        self.player12FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player12FirstName_2.setGeometry(QtCore.QRect(40, 410, 101, 31))
        self.player12FirstName_2.setObjectName("player12FirstName_2")
        self.player13FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player13FirstName_2.setGeometry(QtCore.QRect(40, 440, 101, 31))
        self.player13FirstName_2.setObjectName("player13FirstName_2")
        self.player14FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player14FirstName_2.setGeometry(QtCore.QRect(40, 470, 101, 31))
        self.player14FirstName_2.setObjectName("player14FirstName_2")
        self.player18FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player18FirstName_2.setGeometry(QtCore.QRect(40, 590, 101, 31))
        self.player18FirstName_2.setObjectName("player18FirstName_2")
        self.player17FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player17FirstName_2.setGeometry(QtCore.QRect(40, 560, 101, 31))
        self.player17FirstName_2.setObjectName("player17FirstName_2")
        self.player16FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player16FirstName_2.setGeometry(QtCore.QRect(40, 530, 101, 31))
        self.player16FirstName_2.setObjectName("player16FirstName_2")
        self.player19FirstName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player19FirstName_2.setGeometry(QtCore.QRect(40, 620, 101, 31))
        self.player19FirstName_2.setObjectName("player19FirstName_2")
        self.player6LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player6LastName_2.setGeometry(QtCore.QRect(150, 230, 101, 31))
        self.player6LastName_2.setObjectName("player6LastName_2")
        self.player9LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player9LastName_2.setGeometry(QtCore.QRect(150, 320, 101, 31))
        self.player9LastName_2.setObjectName("player9LastName_2")
        self.player1LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player1LastName_2.setGeometry(QtCore.QRect(150, 80, 101, 31))
        self.player1LastName_2.setObjectName("player1LastName_2")
        self.player12LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player12LastName_2.setGeometry(QtCore.QRect(150, 410, 101, 31))
        self.player12LastName_2.setObjectName("player12LastName_2")
        self.player2LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player2LastName_2.setGeometry(QtCore.QRect(150, 110, 101, 31))
        self.player2LastName_2.setObjectName("player2LastName_2")
        self.player4LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player4LastName_2.setGeometry(QtCore.QRect(150, 170, 101, 31))
        self.player4LastName_2.setObjectName("player4LastName_2")
        self.player14LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player14LastName_2.setGeometry(QtCore.QRect(150, 470, 101, 31))
        self.player14LastName_2.setObjectName("player14LastName_2")
        self.player18LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player18LastName_2.setGeometry(QtCore.QRect(150, 590, 101, 31))
        self.player18LastName_2.setObjectName("player18LastName_2")
        self.player13LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player13LastName_2.setGeometry(QtCore.QRect(150, 440, 101, 31))
        self.player13LastName_2.setObjectName("player13LastName_2")
        self.player0LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player0LastName_2.setGeometry(QtCore.QRect(150, 50, 101, 31))
        self.player0LastName_2.setObjectName("player0LastName_2")
        self.player15LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player15LastName_2.setGeometry(QtCore.QRect(150, 500, 101, 31))
        self.player15LastName_2.setObjectName("player15LastName_2")
        self.player5LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player5LastName_2.setGeometry(QtCore.QRect(150, 200, 101, 31))
        self.player5LastName_2.setObjectName("player5LastName_2")
        self.player8LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player8LastName_2.setGeometry(QtCore.QRect(150, 290, 101, 31))
        self.player8LastName_2.setObjectName("player8LastName_2")
        self.player11LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player11LastName_2.setGeometry(QtCore.QRect(150, 380, 101, 31))
        self.player11LastName_2.setObjectName("player11LastName_2")
        self.player10LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player10LastName_2.setGeometry(QtCore.QRect(150, 350, 101, 31))
        self.player10LastName_2.setObjectName("player10LastName_2")
        self.player17LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player17LastName_2.setGeometry(QtCore.QRect(150, 560, 101, 31))
        self.player17LastName_2.setObjectName("player17LastName_2")
        self.player3LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player3LastName_2.setGeometry(QtCore.QRect(150, 140, 101, 31))
        self.player3LastName_2.setObjectName("player3LastName_2")
        self.player19LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player19LastName_2.setGeometry(QtCore.QRect(150, 620, 101, 31))
        self.player19LastName_2.setObjectName("player19LastName_2")
        self.player16LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player16LastName_2.setGeometry(QtCore.QRect(150, 530, 101, 31))
        self.player16LastName_2.setObjectName("player16LastName_2")
        self.player7LastName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.player7LastName_2.setGeometry(QtCore.QRect(150, 260, 101, 31))
        self.player7LastName_2.setObjectName("player7LastName_2")
        self.label_19 = QtWidgets.QLabel(self.team2)
        self.label_19.setGeometry(QtCore.QRect(10, 110, 31, 31))
        self.label_19.setObjectName("label_19")
        self.label_22 = QtWidgets.QLabel(self.team2)
        self.label_22.setGeometry(QtCore.QRect(10, 260, 31, 31))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.team2)
        self.label_23.setGeometry(QtCore.QRect(10, 140, 31, 31))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.team2)
        self.label_24.setGeometry(QtCore.QRect(10, 170, 31, 31))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.team2)
        self.label_25.setGeometry(QtCore.QRect(10, 230, 31, 31))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.team2)
        self.label_26.setGeometry(QtCore.QRect(10, 200, 31, 31))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.team2)
        self.label_27.setGeometry(QtCore.QRect(10, 80, 31, 31))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.team2)
        self.label_28.setGeometry(QtCore.QRect(10, 320, 31, 31))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.team2)
        self.label_29.setGeometry(QtCore.QRect(10, 380, 31, 31))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.team2)
        self.label_30.setGeometry(QtCore.QRect(10, 410, 31, 31))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.team2)
        self.label_31.setGeometry(QtCore.QRect(10, 290, 31, 31))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.team2)
        self.label_32.setGeometry(QtCore.QRect(10, 470, 31, 31))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.team2)
        self.label_33.setGeometry(QtCore.QRect(10, 350, 31, 31))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.team2)
        self.label_34.setGeometry(QtCore.QRect(10, 440, 31, 31))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.team2)
        self.label_35.setGeometry(QtCore.QRect(10, 530, 31, 31))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.team2)
        self.label_36.setGeometry(QtCore.QRect(10, 590, 31, 31))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.team2)
        self.label_37.setGeometry(QtCore.QRect(10, 620, 31, 31))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.team2)
        self.label_38.setGeometry(QtCore.QRect(10, 500, 31, 31))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.team2)
        self.label_39.setGeometry(QtCore.QRect(10, 560, 31, 31))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.team2)
        self.label_40.setGeometry(QtCore.QRect(10, 50, 31, 31))
        self.label_40.setObjectName("label_40")
        self.teamName_2 = QtWidgets.QPlainTextEdit(self.team2)
        self.teamName_2.setGeometry(QtCore.QRect(90, 10, 104, 31))
        self.teamName_2.setObjectName("teamName_2")
        self.startGame = QtWidgets.QPushButton(self.centralwidget)
        self.startGame.setGeometry(QtCore.QRect(50, 680, 93, 28))
        self.startGame.setObjectName("startGame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 634, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "2"))
        self.label_2.setText(_translate("MainWindow", "7"))
        self.label_3.setText(_translate("MainWindow", "3"))
        self.label_4.setText(_translate("MainWindow", "4"))
        self.label_5.setText(_translate("MainWindow", "6"))
        self.label_6.setText(_translate("MainWindow", "5"))
        self.label_7.setText(_translate("MainWindow", "1"))
        self.label_8.setText(_translate("MainWindow", "9"))
        self.label_9.setText(_translate("MainWindow", "11"))
        self.label_10.setText(_translate("MainWindow", "12"))
        self.label_11.setText(_translate("MainWindow", "8"))
        self.label_12.setText(_translate("MainWindow", "14"))
        self.label_13.setText(_translate("MainWindow", "10"))
        self.label_14.setText(_translate("MainWindow", "13"))
        self.label_15.setText(_translate("MainWindow", "16"))
        self.label_16.setText(_translate("MainWindow", "18"))
        self.label_17.setText(_translate("MainWindow", "19"))
        self.label_18.setText(_translate("MainWindow", "15"))
        self.label_20.setText(_translate("MainWindow", "17"))
        self.label_21.setText(_translate("MainWindow", "0"))
        self.teamName.setPlainText(_translate("MainWindow", "Red Team"))
        self.label_19.setText(_translate("MainWindow", "2"))
        self.label_22.setText(_translate("MainWindow", "7"))
        self.label_23.setText(_translate("MainWindow", "3"))
        self.label_24.setText(_translate("MainWindow", "4"))
        self.label_25.setText(_translate("MainWindow", "6"))
        self.label_26.setText(_translate("MainWindow", "5"))
        self.label_27.setText(_translate("MainWindow", "1"))
        self.label_28.setText(_translate("MainWindow", "9"))
        self.label_29.setText(_translate("MainWindow", "11"))
        self.label_30.setText(_translate("MainWindow", "12"))
        self.label_31.setText(_translate("MainWindow", "8"))
        self.label_32.setText(_translate("MainWindow", "14"))
        self.label_33.setText(_translate("MainWindow", "10"))
        self.label_34.setText(_translate("MainWindow", "13"))
        self.label_35.setText(_translate("MainWindow", "16"))
        self.label_36.setText(_translate("MainWindow", "18"))
        self.label_37.setText(_translate("MainWindow", "19"))
        self.label_38.setText(_translate("MainWindow", "15"))
        self.label_39.setText(_translate("MainWindow", "17"))
        self.label_40.setText(_translate("MainWindow", "0"))
        self.teamName_2.setPlainText(_translate("MainWindow", "Green Team"))
        self.startGame.setText(_translate("MainWindow", "Start Game"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
